datasets:
- batch_size: 16
  epochs: 1
  eval_split: train
  label_column: label
  learning_rate: 2.0e-05
  name: iastate/onestop_english
  text_column: text
  train_split: train
  type: classification
freeze_base: true
model: prajjwal1/bert-tiny
output_dir: results
runs: 3
seed: 42
