datasets:
- name: turkish-nlp-suite/turkish-wikiNER
  type: token_classification
  text_column: text
  tokens_column: tokens
  tags_column: tags
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/beyazperde-all-movie-reviews
  type: regression
  text_column: text
  label_column: star
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/SentiTurca
  type: classification
  subset: e-commerce
  text_column: text
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/SentiTurca
  type: classification
  subset: hate
  text_column: text
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/SentiTurca
  type: classification
  subset: movies
  text_column: text
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/TrCOLA
  type: classification
  text_column: variation
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/TurkishHateMap
  type: classification
  subset: [animals, cities, ethnicity, lgbt, misogyny, occupations, political-orientation, politics, refugees, religion, sects, veganism]
  text_column: text
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/MusteriYorumlari
  type: classification
  text_column: text
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/BuyukSinema
  type: classification
  text_column: text
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/sinefil-movie-reviews
  type: regression
  text_column: text
  label_column: score
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/vitamins-supplements-reviews
  type: regression
  text_column: text
  label_column: star
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: turkish-nlp-suite/beyazperde-top-300-movie-reviews
  type: regression
  text_column: text
  label_column: star
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
- name: mrbesher/offenseval2020_tr
  type: classification
  text_column: text
  label_column: label
  train_split: train
  eval_split: test
  epochs: 3
  batch_size: 16
  learning_rate: 2.0e-05
freeze_base: true
model: dbmdz/bert-base-turkish-cased
output_dir: results
runs: 3
seed: 42