datasets:
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/SentiTurca
  subset: e-commerce
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/SentiTurca
  subset: hate
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/SentiTurca
  subset: movies
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/TrCOLA
  text_column: variation
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/TurkishHateMap
  subset: [animals, cities, ethnicity, lgbt, misogyny, occupations, political-orientation, politics, refugees, religion, sects, veganism]
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/MusteriYorumlari
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/BuyukSinema
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  name: turkish-nlp-suite/turkish-wikiNER
  tags_column: tags
  text_column: text
  tokens_column: tokens
  train_split: train
  type: token_classification
freeze_base: true
model: dbmdz/bert-base-turkish-cased
output_dir: results
runs: 5
seed: 42
