datasets:
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/SentiTurca
  subset: e-commerce
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/SentiTurca
  subset: hate
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/SentiTurca
  subset: movies
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TrCOLA
  text_column: variation
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: animals
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: cities
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: ethnicity
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: lgbt
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: misogyny
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: occupations
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: political-orientation
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: politics
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: refugees
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: religion
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: sects
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: validation
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/TurkishHateMap
  subset: veganism
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/MusteriYorumlari
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/BuyukSinema
  text_column: text
  train_split: train
  type: classification
- batch_size: 16
  epochs: 3
  eval_split: test
  label_column: label
  learning_rate: 2.0e-05
  max_length: 128
  name: turkish-nlp-suite/turkish-wikiNER
  tags_column: tags
  text_column: text
  tokens_column: tokens
  train_split: train
  type: token_classification
freeze_base: true
model: dbmdz/bert-base-turkish-cased
output_dir: results_turkish
runs: 3
seed: 42
